# Generated by Django 2.2.11 on 2020-03-14 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0033_auto_20200314_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='admins',
        ),
    ]
